services:
  meal-service:
    container_name: meal-service
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "<호스트포트>:<컨테이너포트>"
    networks:
      - sandol-network
    depends_on:
      - meal-service-db

  meal-service-db:
    container_name: meal-service-db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - sandol-network

networks:
  sandol-network:
    driver: bridge

volumes:
  db_data:
