"""add user fields

Revision ID: 3297eb691f3b
Revises: 133210f0f0b5
Create Date: 2026-01-18 13:50:21.620237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3297eb691f3b'
down_revision: Union[str, None] = '133210f0f0b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('user_id', sa.String(), nullable=False))
    op.add_column('User', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_User_user_id'), 'User', ['user_id'], unique=True)
    op.drop_column('User', 'meal_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('meal_admin', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_User_user_id'), table_name='User')
    op.drop_column('User', 'created_at')
    op.drop_column('User', 'user_id')
    # ### end Alembic commands ###
