"""empty message

Revision ID: 839cd699aac5
Revises: 28554ef143ac
Create Date: 2025-03-10 19:37:27.219740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '839cd699aac5'
down_revision: Union[str, None] = '28554ef143ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Restaurant_submission', sa.Column('reviewer', sa.Integer(), nullable=True))
    op.add_column('Restaurant_submission', sa.Column('reviewed_time', sa.DateTime(timezone=True), server_default='2025-03-10T10:37:27.094+00:00', nullable=True))
    op.add_column('Restaurant_submission', sa.Column('rejection_message', sa.Text(), nullable=True))
    op.drop_column('Restaurant_submission', 'approver')
    op.drop_column('Restaurant_submission', 'approved_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Restaurant_submission', sa.Column('approved_time', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('Restaurant_submission', sa.Column('approver', sa.INTEGER(), nullable=True))
    op.drop_column('Restaurant_submission', 'rejection_message')
    op.drop_column('Restaurant_submission', 'reviewed_time')
    op.drop_column('Restaurant_submission', 'reviewer')
    # ### end Alembic commands ###
